center=[1,1,3];
radius=1;
u1=[1,1,0];
u1=u1/norm(u1);
radian1=pi/6;
figure;
drawSphericalCap(center,radius,u1,radian1,'FaceColor','blue');
hold on;
drawSphericalSector(center,radius,u1,radian1);
[bottom,top]=computeBoundingBoxForSphericalCap(u1,radian1);
bottom=bottom*radius+center;
top=top*radius+center;
draw3DBoundingBox(bottom(1),bottom(2),bottom(3),top(1),top(2),top(3),'color','blue');
axis equal;
grid off;
hold off;
axis off;
light('Color',[0.8, 0.8, 0.8],'Position',[10 10 -10],'Style','infinite');
camlight;