% center=[0,0,0];
% radius=1;
% u=[-1,1,0];
% u=u/norm(u);
% radian=2*pi/3;
center = [0, 3, 0];%[0, -3, 0]
radius = 2;
n = [1, 0, 0];
n=n/norm(n);
u=[0.8575, 0,-0.5145];
u=u/norm(u);
radian=1*pi/3;
drawSphericalSector(center,radius,u,radian);
[bottom,top]=computeBoundingBoxForSphericalSector(u,radian);
bottom=bottom*radius+center;
top=top*radius+center;
draw3DBoundingBox(bottom(1),bottom(2),bottom(3),top(1),top(2),top(3),'color','blue');
grid off;
hold off;
%axis off;
xlabel('x');
ylabel('y');
zlabel('z');
light('Color',[0.8, 0.8, 0.8],'Position',[10 10 -10],'Style','infinite');
camlight;
axis equal;